### PR TITLE
Rename directory name of example flows

### PR DESCRIPTION
**Pull request by zuhito**
I'd like to suggest the directory name, "examples" for flow files instead of the current directory name, "example_flows" because Node-RED users can import the flows via import menu on their Node-RED flow editor.

flow

### CODE REVIEW

**Comment by ptitzler** [comment]
Are you saying that if we rename the directory and republish the module the flows will automagically show up under examples? That'd be awesome.

**Comment by ptitzler** [comment]
As a side node, is there possibly a bug in the UI? The menu entry is named `model asset-exchange` (note the hyphen) instead of `model asset exchange`?

**Comment by zuhito** [comment]
Yes, it is a bug in Node-RED. I'm going to solve this problem next week.

**Comment by zuhito** [comment]
I fixed the bug of Node-RED UI. The next version, Node-RED v0.20 will show menu entries correctly.

**Pull request merged**
